package GUI;

import Game.*;
import PlayerBehavior.Estimate;
import PlayerBehavior.TakeLetter;
import PlayerInformation.ReaderAndWriterFileProcess;
import PlayerInformation.RegisterAndSignIn;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author alise
 */
public class cardPanel extends javax.swing.JPanel {

    protected RegisterAndSignIn registerAndSign = new RegisterAndSignIn();
    protected Player normalPlayer, adminPlayer;

 
    public cardPanel() {
        initComponents();
    }

    public void showSignIn() {
        jTabbedPaneSıgnInAndRegister.setSelectedIndex(0);
    }

    public void showRegister() {
        jTabbedPaneSıgnInAndRegister.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSıgnInAndRegister = new javax.swing.JTabbedPane();
        jPanelSignIn = new javax.swing.JPanel();
        jLabelSignInNickname1 = new javax.swing.JLabel();
        jLabelSignInPassword1 = new javax.swing.JLabel();
        jTextFieldSignInNickname = new javax.swing.JTextField();
        jButtonSignInPlay1 = new javax.swing.JButton();
        jButtonMainmenu = new javax.swing.JButton();
        jPasswordFieldSıgnIn = new javax.swing.JPasswordField();
        jPanelRegister = new javax.swing.JPanel();
        jLabelRegisterNickname = new javax.swing.JLabel();
        jLabelRegisterPassword1 = new javax.swing.JLabel();
        jLabelRegisterPassword2 = new javax.swing.JLabel();
        jTextFieldRegisterNickname = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jPasswordFieldRegister = new javax.swing.JPasswordField();
        jPasswordFieldRegisterCheck = new javax.swing.JPasswordField();
        jButtonMainMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(20, 30, 50));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPaneSıgnInAndRegister.setBackground(new java.awt.Color(20, 30, 50));
        jTabbedPaneSıgnInAndRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPaneSıgnInAndRegister.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPaneSıgnInAndRegister.setOpaque(true);

        jPanelSignIn.setBackground(new java.awt.Color(20, 30, 50));

        jLabelSignInNickname1.setBackground(new java.awt.Color(255, 215, 0));
        jLabelSignInNickname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSignInNickname1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelSignInNickname1.setText("Nickname:");

        jLabelSignInPassword1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSignInPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSignInPassword1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelSignInPassword1.setText("Password:");

        jTextFieldSignInNickname.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldSignInNickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSignInNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldSignInNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignInNicknameActionPerformed(evt);
            }
        });

        jButtonSignInPlay1.setBackground(new java.awt.Color(255, 215, 0));
        jButtonSignInPlay1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSignInPlay1.setForeground(new java.awt.Color(20, 30, 50));
        jButtonSignInPlay1.setText("PLAY");
        jButtonSignInPlay1.setFocusPainted(false);
        jButtonSignInPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInPlay1ActionPerformed(evt);
            }
        });

        jButtonMainmenu.setBackground(new java.awt.Color(102, 0, 0));
        jButtonMainmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMainmenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMainmenu.setText("EXIT");
        jButtonMainmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonMainmenu.setFocusPainted(false);
        jButtonMainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainmenuActionPerformed(evt);
            }
        });

        jPasswordFieldSıgnIn.setBackground(new java.awt.Color(255, 215, 0));
        jPasswordFieldSıgnIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldSıgnIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordFieldSıgnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSıgnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
        jPanelSignIn.setLayout(jPanelSignInLayout);
        jPanelSignInLayout.setHorizontalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSignInLayout.createSequentialGroup()
                                .addComponent(jLabelSignInNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSignInLayout.createSequentialGroup()
                                .addComponent(jLabelSignInPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldSıgnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelSignInLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSignInPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelSignInLayout.setVerticalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSıgnIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignInPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPaneSıgnInAndRegister.addTab("Sign-In", jPanelSignIn);

        jPanelRegister.setBackground(new java.awt.Color(20, 30, 50));

        jLabelRegisterNickname.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterNickname.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterNickname.setText("Nickname:");

        jLabelRegisterPassword1.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterPassword1.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword1.setText("Password:");

        jLabelRegisterPassword2.setBackground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegisterPassword2.setForeground(new java.awt.Color(255, 215, 0));
        jLabelRegisterPassword2.setText("Password Again:");

        jTextFieldRegisterNickname.setBackground(new java.awt.Color(255, 215, 0));
        jTextFieldRegisterNickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldRegisterNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldRegisterNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterNicknameActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(255, 215, 0));
        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(20, 30, 50));
        jButtonRegister.setText("SAVE");
        jButtonRegister.setFocusPainted(false);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jPasswordFieldRegister.setBackground(new java.awt.Color(255, 215, 0));
        jPasswordFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordFieldRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRegisterActionPerformed(evt);
            }
        });

        jPasswordFieldRegisterCheck.setBackground(new java.awt.Color(255, 215, 0));
        jPasswordFieldRegisterCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldRegisterCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonMainMenu.setBackground(new java.awt.Color(102, 0, 0));
        jButtonMainMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMainMenu.setText("EXIT");
        jButtonMainMenu.setFocusPainted(false);
        jButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                            .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                            .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordFieldRegister))
                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                            .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordFieldRegisterCheck))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldRegisterCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        jTabbedPaneSıgnInAndRegister.addTab("Register", jPanelRegister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jTabbedPaneSıgnInAndRegister)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jTabbedPaneSıgnInAndRegister)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSignInNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignInNicknameActionPerformed

    }//GEN-LAST:event_jTextFieldSignInNicknameActionPerformed

    private void jButtonSignInPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInPlay1ActionPerformed

        String nickname = jTextFieldSignInNickname.getText().trim();
        String password = jPasswordFieldSıgnIn.getText().trim();

        int result = -1;
        try {
            result = registerAndSign.signIn(nickname, password);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }

        if (result == 0) {
            adminPlayer = new Admin();

            new AdminFrame().setVisible(true);

            JOptionPane.showMessageDialog(this, adminPlayer.displayWhichPlayer());

            SwingUtilities.getWindowAncestor(this).dispose();
        } else if (result == 1) {
            try {
                normalPlayer = new NormalPlayer(
                        nickname,
                        ReaderAndWriterFileProcess.getterLastIdFromFile(nickname),
                        new TakeLetter(),
                        new Estimate()
                );
            } catch (IOException ex) {
                System.out.println(ex.toString());

            }

            JOptionPane.showMessageDialog(this, "Game Started!! \n"+normalPlayer.displayWhichPlayer());

            try {
                new GameFrame(normalPlayer).setVisible(true);
                SwingUtilities.getWindowAncestor(this).dispose();

            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(cardPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        } else { // Hatalı giriş
            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre hatalı!");

            jTextFieldSignInNickname.setText("");
            jPasswordFieldSıgnIn.setText("");
        }

    }//GEN-LAST:event_jButtonSignInPlay1ActionPerformed

    private void jButtonMainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainmenuActionPerformed

        SwingUtilities.getWindowAncestor(this).dispose();

        MainMenuFrame frame = new MainMenuFrame();
        frame.setVisible(true);


    }//GEN-LAST:event_jButtonMainmenuActionPerformed

    private void jTextFieldRegisterNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterNicknameActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed

        String nickname = jTextFieldRegisterNickname.getText().trim();
        String password1 = jPasswordFieldRegister.getText().trim();
        String password2 = jPasswordFieldRegisterCheck.getText().trim();

        if (nickname.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter valid nickname and password!",
                    "Giriş Hatası",
                    JOptionPane.ERROR_MESSAGE);
            return; // Kodun geri kalanını çalıştırmadan metoddan çık
        }
        try {
            if (registerAndSign.register(nickname, password1, password2)) {

                JOptionPane.showMessageDialog(this, "Kayıt başarılı!");
                jTextFieldRegisterNickname.setText("");
                jPasswordFieldRegister.setText("");
                jPasswordFieldRegisterCheck.setText("");
                showSignIn();
            } else {
                JOptionPane.showMessageDialog(this, "Kayıt başarısız!");
                jTextFieldRegisterNickname.setText("");
                jPasswordFieldRegister.setText("");
                jPasswordFieldRegisterCheck.setText("");
            }
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(cardPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jPasswordFieldSıgnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSıgnInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSıgnInActionPerformed

    private void jPasswordFieldRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRegisterActionPerformed

    private void jButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMenuActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();

        MainMenuFrame frame = new MainMenuFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonMainMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMainMenu;
    private javax.swing.JButton jButtonMainmenu;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSignInPlay1;
    private javax.swing.JLabel jLabelRegisterNickname;
    private javax.swing.JLabel jLabelRegisterPassword1;
    private javax.swing.JLabel jLabelRegisterPassword2;
    private javax.swing.JLabel jLabelSignInNickname1;
    private javax.swing.JLabel jLabelSignInPassword1;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPanel jPanelSignIn;
    private javax.swing.JPasswordField jPasswordFieldRegister;
    private javax.swing.JPasswordField jPasswordFieldRegisterCheck;
    private javax.swing.JPasswordField jPasswordFieldSıgnIn;
    private javax.swing.JTabbedPane jTabbedPaneSıgnInAndRegister;
    private javax.swing.JTextField jTextFieldRegisterNickname;
    private javax.swing.JTextField jTextFieldSignInNickname;
    // End of variables declaration//GEN-END:variables
}
